import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./stores/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      xs: "475px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "4rem",
          xl: "5rem",
          "2xl": "6rem",
        },
        screens: {
          sm: "640px",
          md: "768px",
          lg: "1024px",
          xl: "1280px",
          "2xl": "1536px",
        },
      },
      fontFamily: {
        legquinne: ["Legquinne-light", "system-ui", "sans-serif"],
        sukar: ["Sukar", "Legquinne-light", "system-ui", "sans-serif"],
        sans: ["Legquinne-light", "system-ui", "sans-serif"],
        en: ["Legquinne-light", "system-ui", "sans-serif"],
        ar: ["Sukar Black Font", "Legquinne-light", "system-ui", "sans-serif"],
      },
      fontSize: {
        xs: ".625rem",
        sm: ".75rem",
        md: ".875rem",
        xmd: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.75rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
        "6xl": "3rem",
        "7xl": "4rem",
        "8xl": "5rem",
        "9xl": "6rem",
      },
      spacing: {
        "18": "4.5rem",
        "88": "22rem",
        "128": "32rem",
      },
      colors: {
        primary: {
          "50": "#EFF2F1",
          "100": "#CED6D5",
          "200": "#B6C2C0",
          "300": "#94A6A3",
          "400": "#809591",
          "500": "#607A76",
          "600": "#576F6B",
          "700": "#445754",
          "800": "#354341",
          "900": "#283332",
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          "50": "#EBEBEB",
          "100": "#C0C0C0",
          "300": "#767676",
          "400": "#5C5C5C",
          "500": "#333333",
          "600": "#2E2E2E",
          "700": "#242424",
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        white: {
          "50": "#FDFEFE",
          "100": "#FFFFFF",
          "200": "#F6F9FA",
          "300": "#E6E6E6",
          "400": "#D9D9D9",
          "500": "#ECF1F4",
          "600": "#B3B3B3",
          DEFAULT: "#FFFFFF",
        },
        black: {
          "500": "#252424",
          "600": "#2E2E2E",
          "700": "#242424",
        },
        button: {
          "background-primary": "#607A76",
          "background-primary-disable": "#CED6D5",
          "background-secondary": "#333333",
          "background-secondary-disable": "#2E2E2E",
          "background-tertiary": "#2E2E2E",
          "background-tertiary-disable": "#242424",
          "background-quaternary": "#242424",
          "background-quaternary-disable": "#1C1C1C",
          "background-quinary": "#1C1C1C",
          "background-quinary-disable": "#141414",
          "background-senary": "#141414",
          "background-senary-disable": "#0A0A0A",
          "background-septenary": "#0A0A0A",
          "background-septenary-disable": "#000000",
          "background-icon": "#FDFEFE29",
          "icon-border": "#373737",
        },
        gray: {
          "500": "#CECECE",
          "600": "#A0A0A0",
          "950": "#1C1C1C",
        },

        custom: {
          translucentDark: "#2424243D",
          backgroundLight: "#F2F2F2",
          borderLight: "#EFEFEF",
        },
        dark: {
          primary: {
            "50": "#EFF2F1",
            "100": "#CED6D5",
            "200": "#B6C2C0",
            "300": "#94A6A3",
            "400": "#809591",
            "500": "#607A76",
            "600": "#576F6B",
            "700": "#445754",
            "800": "#354341",
            "900": "#283332",
            DEFAULT: "hsl(var(--primary))",
            foreground: "hsl(var(--primary-foreground))",
          },
          secondary: {
            "50": "#EBEBEB",
            "100": "#C0C0C0",
            "300": "#767676",
            "400": "#5C5C5C",
            "500": "#333333",
            "600": "#2E2E2E",
            "700": "#242424",
          },
          white: {
            "50": "#FDFEFE",
            "100": "#FFFFFF",
            "200": "#F6F9FA",
            "300": "#E6E6E6",
            "400": "#D9D9D9",
            "500": "#ECF1F4",
            "600": "#B3B3B3",
            DEFAULT: "#FFFFFF",
          },
          black: {
            "500": "#252424",
            "600": "#2E2E2E",
            "700": "#242424",
          },
          button: {
            "background-primary": "#607A76",
            "background-primary-disable": "#E9EFF7",
            "background-secondary": "#333333",
            "background-secondary-disable": "#2E2E2E",
            "background-tertiary": "#2E2E2E",
            "background-tertiary-disable": "#242424",
            "background-quaternary": "#242424",
            "background-quaternary-disable": "#1C1C1C",
            "background-quinary": "#1C1C1C",
            "background-quinary-disable": "#141414",
            "background-senary": "#141414",
            "background-senary-disable": "#0A0A0A",
            "background-septenary": "#0A0A0A",
            "background-septenary-disable": "#000000",
            "background-icon": "#FDFEFE29",
            "icon-border": "#373737",
          },
          gray: {
            "500": "#CECECE",
            "600": "#A0A0A0",
            "950": "#1C1C1C",
          },
          custom: {
            translucentDark: "#2424243D",
            backgroundLight: "#F2F2F2",
            borderLight: "#EFEFEF",
          },
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        shimmer: "shimmer 2s infinite linear",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-rtl"), require("tailwindcss-animate")],
};

export default config;
